name: Lakehouse Connector Release (Manual)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version of the release. Without the `v` prefix'
        required: true
        default: '3.0.5.3'
jobs:
  upload:
    name: Upload Release files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        if: ${{ needs.changed_files_job.outputs.docs_only != 'true' }}
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Login streamnative docker hub
        run: docker login -u="${{ secrets.DOCKER_USER }}" -p="${{ secrets.DOCKER_PASSWORD }}"

      - uses: robinraju/release-downloader@v1.10
        with:
          tag: v${{ inputs.version }}
          fileName: '*'

      - name: build and push docker image
        uses: nick-fields/retry@v2
        env:
            PULSAR_VERSION: ${{ inputs.version }}
            CONNECTOR_VERSION: ${{ inputs.version }}
        with:
          max_attempts: 99
          retry_wait_seconds: 60
          timeout_minutes: 5
          command: |
            mkdir -p target
            mv pulsar-io-lakehouse-*.nar target
            REPO=`mvn -q -Dexec.executable=echo -Dexec.args='${project.artifactId}' --non-recursive exec:exec 2>/dev/null`
            IMAGE_REPO=streamnative/${REPO}
            docker build --build-arg PULSAR_VERSION="$PULSAR_VERSION" -t ${IMAGE_REPO}:${CONNECTOR_VERSION} -f ./image/Dockerfile ./
            docker push ${IMAGE_REPO}:${CONNECTOR_VERSION}
